### ISSUE TITLE
MQTT message buffering during temporary internet connection loss (duplicate messages)

### ISSUE THREAD

**Issue by dkby** [iotblackbelt/node-red-contrib-azure-iot-device#10]
Setting:
Using the node on Weidmueller u-controll web device (node red v1.1.2) . Provisioning with DPS (CA based x509).

Telemetry messages are not buffered when connection is temporally down when amqp is chosen.
However, when using mqtt, messages are buffered for 300s. After that, the node stops with an error.

During this 300s interval, duplicated messages are generated:
For every 15s of downtime, the message is sent out one time. So if, e.g., triggering a message while the device is offline, waiting 60s and reconnecting again, the very same message will be received 4 times by iot hub.

**Comment by iotblackbelt** [comment]
Duplicate.
