### ISSUE TITLE
[Feature] Check connection to IoT Hub

### ISSUE THREAD

**Issue by dkby** [iotblackbelt/node-red-contrib-azure-iot-device#12]
Cyclically check the connection status and update node.status according to the result. Via "status"-nodes, the node-red application should be able to receive changes in the node's connection status. Also, it might be helpful to make parameterize the interval for cyclic check.

**Comment by iotblackbelt** [comment]
@dkby: check is added as part of the issue fix. Will be released with version 0.2.1.
