### ISSUE TITLE
[Feature] Configurable buffering concept in case of connection loss

### ISSUE THREAD

**Issue by dkby** [iotblackbelt/node-red-contrib-azure-iot-device#13]
This would be a quite complex feature. However, if connection status information is available, this buffering could also be implemented by the application that uses this node. Currently, the application has no means of making sure that generated data is transmitted to the cloud.

**Comment by iotblackbelt** [comment]
Store & forward feature is currently part of the Azure IoT Edge platform. This feature will not be implemented in this node for now. Will implement A way to identify whther a message was sent. The application can then take action to resend if needed.
