### ISSUE TITLE
Cannot connect with connection string and without PnP and device provisioning.

### ISSUE THREAD

**Issue by aamrcg** [iotblackbelt/node-red-contrib-azure-iot-device#14]
Hi, 

Been testing the node as an alternative to the other ones out there. Using the example flow.

![image](https://user-images.githubusercontent.com/77668562/108486959-9a0aec00-7296-11eb-938a-78f5bec1acc8.png)

It errors out with a basic setup. 

![image](https://user-images.githubusercontent.com/77668562/108487602-58c70c00-7297-11eb-84cb-10cc9482127b.png)

I'm not using provisioning nor PnP, nor Edge Gateway, but it reports a provisioning error. 
Any thoughts?

Thanks 
Art

**Comment by ghassansalloum** [comment]
I found a bug in the code of the node I think.

When you choose Connection String, the code is still looking for a "Scope ID" value, and that field is only shown when you pick the Device Provisioning Service method. So choose that connection type, fFill in a random string in the scope id field, then go back to "Connection String" and it should get over the "Provisioning' error.   I am hitting a connection error after that, but that's a different issue.   

Note to dev: I found specifically a ProvisioningDeviceClient is created before the code checks if the connection type is "constr" (where presumably the provisioning would not be needed). Is that expected?
![image](https://user-images.githubusercontent.com/9168276/108583081-2398d900-72ec-11eb-8c1d-842d598c1c0b.png)

**Comment by ghassansalloum** [comment]
Additionally, I am trying to figure out if this node is supposed to work with a Device that I _already_ created (via the Azure portal for example). Is it? That's what I thought the choice of "Connection Type = Connection String" is for, and what got me digging in the code wondering why it's complaining about a 'provisioning' error for a device that's already created/provisioned.

**Comment by SillaRizzoli** [comment]
I'm having a similar problem. I've set up a device with connection string and without PnP and device provisioning with the node version 0.2.0 and everything worked. After update to 0.2.1 and 0.2.2 the node stopped working (with 0.2.1 I got a provisioning error and with 0.2.2 I get "Unable to send telemetry, device not connected."

**Comment by iotblackbelt** [comment]
@ghassansalloum, @SillaRizzoli this is the same issue as this [one](https://github.com/iotblackbelt/node-red-contrib-azure-iot-device/issues/16). Will be resolved asap.

**Comment by SillaRizzoli** [comment]
Thanks for fixing it so quickly!
