### ISSUE TITLE
Documentation for "Device ID" should mention it's the "Registration ID" if using the DPS method?

### ISSUE THREAD

**Issue by ghassansalloum** [iotblackbelt/node-red-contrib-azure-iot-device#15]
In reference to: https://github.com/iotblackbelt/node-red-contrib-azure-iot-device/blob/master/CONFIGURE.md

If you're using the Device Provisioning Service connection type, the actual Device ID is defined by the enrollment in the Azure service, not by the node itself. So both the UX interface of this node and the documentation seem inaccurate:
![image](https://user-images.githubusercontent.com/9168276/108602943-d8b5aa80-7359-11eb-8757-318d5c4503ff.png)

As far as I can tell, what the code of this node actually expects to have in case of the DPS method is the "Registration ID" value found in the enrollment configuration in the Azure DPS service:
![image](https://user-images.githubusercontent.com/9168276/108602989-1dd9dc80-735a-11eb-8951-81785705cc55.png)

For more intuitive ease of use of this node, I recommend you create a separate UX field named "Registration ID", and hide the "Device ID" one, and update the code to use the correct one, in case the user has chosen the DPS connection type.

**Comment by iotblackbelt** [comment]
@ghassansalloum If you use group enrollments, the device id that you use in the node will be the device id in IoT Hub. If you use individual enrollment the provided device id will be use as the device id in IoT Hub. I will update the documetation that, in case of individual enrollment the device id in the node should be the same as the registration id.

**Comment by iotblackbelt** [comment]
When doing the update also discovered a bug in the individual registration. Adjusted that as well.

**Comment by iotblackbelt** [comment]
Fixed in version 0.2.3
