### ISSUE TITLE
Connection string seems wrongly constructed in some cases. Device doesn't connect with the SAS method, or with individual-enrollment DPS.  

### ISSUE THREAD

**Issue by ghassansalloum** [iotblackbelt/node-red-contrib-azure-iot-device#16]
The way the Connection String is constructed seems in complete in 0.2.2. in the connectDevice() function.

The code always makes a call to computeDerivedSymmetricKey() when constructing the ConnectionString. 

After some experimentation it turns out that this code does not work with the Connection Type = Connection String, or if the Connection Type = "Device provisioning service" and I configured an individual enrollment (rather than group enrollment).

To make a simple ConnType = Connection string, and Connection type = DPS with the individual enrollment work, I had to 'neutralize' that function (modify it to simply return the node.sas that's passed in, rather than hashing it with the deviceid). When I made that change,  the device finally connected properly, in both modes (Connection Type = Connection String, and Connection Type = Device provisioning service, with an individual enrollment), after 3 days of trying to figure it out! Woot!

UPDATE: I eventually realized you have already addressed this in the provisionDevice() function with this line:
 var saskey = (node.enrollmenttype === "group") ? computeDerivedSymmetricKey(node.saskey, node.deviceid) : node.saskey;
       
It seems it's a miss on your side for the connectDevice() function

**Comment by iotblackbelt** [comment]
@ghassansalloum thanks for finding the issue. It is a result of the last update. I will resolve it asap.

**Comment by iotblackbelt** [comment]
Fixed in version 0.2.3
