### ISSUE TITLE
`Device provisioning failed` is shown though sending telemetry is successful

### ISSUE THREAD

**Issue by dzeyelid** [iotblackbelt/node-red-contrib-azure-iot-device#18]
I wonder about the following behavior. Could you confirm that?

After deploying a flow I got the error message, but sending telemetry is succeeded.

```
[error] [azureiotdevice:b32006bf.0cdd38] test -> Device provisioning failed.
```

The configuration is like the below. (Device ID is correct, that is the actual registered name)

![image](https://user-images.githubusercontent.com/977117/112427288-afcf6d80-8d7c-11eb-85d1-add4a63d351b.png)

Anyway, Thank you for this node. I'm tired of that many other nodes to connect Azure IoT Hub are out of maintenance.

**Comment by iotblackbelt** [comment]
@dzeyelid I will research the issue. Am I correct that you are conecting a device using direct connection string?

**Comment by dzeyelid** [comment]
@iotblackbelt Thanks so much.

Strangely when I retry my node flow to get more information to you, the error message is not shown now... Both of the connection strings that are in shared access policies or linked to a device are available now.

So can I close this issue?
