### ISSUE TITLE
Transitioning from "node-red-contrib-azure-iot-hub" palette

### ISSUE THREAD

**Issue by mgKeeKrog** [iotblackbelt/node-red-contrib-azure-iot-device#19]
Thank you for developing the Azure-IoT-Device palette. The "direct" node works great for my publishing and direct method needs. I have tested my application offline and am trying to incrementally incorporate the new "direct" node into a production system that includes 25 flows, each flow communicating with various subsystems on various communication protocols (Modbus, SNMP, OPC, etc.). My existing production system uses the "node-red-contrib-azure-iot-hub" palette for just publishing telemetry in each of the 25 flows. 

When I edited the first flow to include the "direct" node I noticed all IoT nodes from the legacy palette stopped publishing telemetry to the IoTHub. I was hoping to replace one flow at a time in the production system but this result creates a problem. Is this a know problem? Is there any work around? Thank you.

**Comment by mgKeeKrog** [comment]
Related to the above I've tried everything I could think of:  export/reimport, edit node one at a time and redeploy, restart the controller, etc. All "direct" nodes are publishing duplicate payloads to IoT Hub but everything is very stable and reliable. I just don't want to be publishing double the payloads than what is necessary. Thank you.

**Comment by BC-josgreeve** [comment]
same issue here, all the payloads (twins) are being published even to nodes without those 'properties'

**Comment by iotblackbelt** [comment]
@mgKeeKrog @BC-josgreeve thanks for reporting. I haven't tested using my node next to the "node-red-contrib-azure-iot-hub" palette. As my node uses the latest SDK and the "old" node isn't updated, this can be an issue. I will check it out. Will also check the duplicate messages and twins. Each Azure IoT Device created with my "node-red-contrib-azure-iot-device" should be individually addressable as twin.

**Comment by iotblackbelt** [comment]
Closing issue. Couldn't reproduce.
