### ISSUE TITLE
Node-Red device fails provisioning using CA certificates

### ISSUE THREAD

**Issue by adnorin** [iotblackbelt/node-red-contrib-azure-iot-device#21]
Please see my post here...
https://discourse.nodered.org/t/node-red-azure-iot-hub-provisioning-issues/46059

I have tried different certificates so far all with the same result. "Device Provisioning Failure".  I have tested these certificates using the same IoT Hub and device using other methods and they work.  The node works well with SAS key. Please let me know if you have been able to use this using certificates, and please explain how. Thank you.

**Comment by iotblackbelt** [comment]
@adnorin I will very the working and let you know the outcome.

**Comment by iotblackbelt** [comment]
> Please see my post here...
> https://discourse.nodered.org/t/node-red-azure-iot-hub-provisioning-issues/46059
> 
> I have tried different certificates so far all with the same result. "Device Provisioning Failure". I have tested these certificates using the same IoT Hub and device using other methods and they work. The node works well with SAS key. Please let me know if you have been able to use this using certificates, and please explain how. Thank you.

@adnorin can you please share the way you create the certificates? Are you using the self-signed certificate approach? https://docs.microsoft.com/en-us/azure/iot-hub/tutorial-x509-self-sign

**Comment by iotblackbelt** [comment]
Issue fixed, will be released in 0.2.4 version.
