### ISSUE TITLE
Commands defined within scope of "Components" are not processed (Azure IOT Central)

### ISSUE THREAD

**Issue by peterheldens** [iotblackbelt/node-red-contrib-azure-iot-device#22]
Commands defined in the **Root** of Azure IoT Central are processed/received by the azure-iot-device node. However, Commands defined within **Components** seem not to be received by the azure-iot-device node. As example in the screenshot, the Blink and Cmd commands are not received in the azure-iot-device node. The Message command (defined in the Root) is processed correctly.

![image](https://user-images.githubusercontent.com/6528420/120190575-13f92c80-c219-11eb-841c-f4e277210358.png)
![image](https://user-images.githubusercontent.com/6528420/120191317-1445f780-c21a-11eb-9b3d-5cef546715a7.png)

**Comment by iotblackbelt** [comment]
@peterheldens can you try using the full command name in the device definition? When using components the command names are actually including the component name. So in your case define the direct method as "control*cmd" and "control*blink". Please let me know if this works?

**Comment by iotblackbelt** [comment]
> @peterheldens can you try using the full command name in the device definition? When using components the command names are actually including the component name. So in your case define the direct method as "control_cmd" and "control_blink". Please let me know if this works?

I tested it and it actually works:
![image](https://user-images.githubusercontent.com/33823558/123094912-b75eeb00-d42d-11eb-9603-6bf43349d17c.png)
(IoT Central raw message}

![image](https://user-images.githubusercontent.com/33823558/123094754-90081e00-d42d-11eb-870e-d8a685f80367.png)
(Method in node-red)
