### ISSUE TITLE
New device on another flow: message "leakage" between devices?

### ISSUE THREAD

**Issue by packnologyusa** [iotblackbelt/node-red-contrib-azure-iot-device#25]
Hi,
I've opened a ticket with IOT Central about this but thought I should check here as well. I have set up a new device node with a new connection on a new flow. In IOT Central I'm seeing data for a different (existing) device (different connection on another flow) showing up in the Raw Data for the new device. Is this an IOT Central bug, or are messages getting routed to the wrong device for some reason? Are there any known issues with multiple device connections?
Thanks,
Greg

**Comment by packnologyusa** [comment]
FYI I just checked on the IoT Hub side, and the messages are definitely getting sent via the wrong device connection. So it looks like there is a problem when there's more than 1 device connection on the same node-red instance (even when they're in different flows).

**Comment by sandervandevelde** [comment]
Note: See also [MS Learn](https://docs.microsoft.com/en-us/answers/questions/546488/raw-data-view-for-a-device-shows-data-from-other-d.html?childToView=547896#comment-547896)

**Comment by iotblackbelt** [comment]
Will research. Should be possible to have multiple devices represented, each by its own device node.

**Comment by sandervandevelde** [comment]
I was able to replay this yesterday on Win10 OS with latest stable NodeRed.

**Comment by iotblackbelt** [comment]
@packnology this was a bug in the node code. I have fixed it and am testing it.

**Comment by iotblackbelt** [comment]
Will be resolve in 0.2.4. Bug in node code didn't isolate individual Azure IoT device clients.
