### ISSUE TITLE
Why is SAS key visible in logging

### ISSUE THREAD

**Issue by sandervandevelde** [iotblackbelt/node-red-contrib-azure-iot-device#26]
Hello,

I notice the connection string is shown in the logging, complete with SAS key:

![image](https://user-images.githubusercontent.com/694737/139756702-cac15100-34a6-47cd-8515-2f5394e6a231.png)

It seems the connection string is written in the log without extra obfuscation of the secret:

    node.log(node.deviceid + ' -> Connection string: ' + connectionString);

Please remove the SAS key.

**Comment by iotblackbelt** [comment]
Will update, but to see the logging will have to have sufficient access to the machine. That access will also allow you to have access to node-red, therefore obscuring it here won't make it more secure. The security improvement will have to be found in hardening and securing the machine that runs the server.

**Comment by iotblackbelt** [comment]
Will be resolved in 0.2.4. No logging of connection string.
