### ISSUE TITLE
Support for iothub-creation-time-utc when sending telemetry

### ISSUE THREAD

**Issue by hixfield** [iotblackbelt/node-red-contrib-azure-iot-device#28]
Referring to https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-messages-construct#application-properties-of-d2c-iot-hub-messages I would like to have support for the "iothub-creation-time-utc" application property when sending telemetry.

Notice that this value is encapsulated into a JSON sub-object "messageProperties" and not the "telemetry". I looked at the node.js code and as far as I can see, this means we cannot simply add it by manipulating the Node message coming into the node e.g. payload.iothub-creation-time-utx = xxxx.

**Comment by sandervandevelde** [comment]
Hello @hixfield ,

an IoT message is divided into three parts:
- the message body (a byte array, usually filled with a JSON message)
- application properties (a property bag) aka user properties
- system properties (a property bag)

A device can only send the body and the user properties, not system properties.

The node support adding [user properties](https://github.com/iotblackbelt/node-red-contrib-azure-iot-device/blob/ab1ecb1bb98f7e12830ce87c464c8406dd5901a2/azureiotdevice/azureiotdevice.js#L168) as part of the message. 

So, you can add any property, including 'iothub-creation-time-utc', yourself.

**Comment by hixfield** [comment]
@sandervandevelde I'm confused.

As stated by Microsoft here https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-messages-construct#application-properties-of-d2c-iot-hub-messages  the `iothub-creation-time-utc` is an application property and they indicate:

"_A common use of application properties is to send a timestamp from the device using the iothub-creation-time-utc property to record when the message was sent by the device._"

 this to me tells me that the device (in our case Node-RED)  can send this following their specified structure in the example:

```
{
  "applicationId":"5782ed70-b703-4f13-bda3-1f5f0f5c678e",
  "messageSource":"telemetry",
  "deviceId":"sample-device-01",
  "schema":"default@v1",
  "templateId":"urn:modelDefinition:mkuyqxzgea:e14m1ukpn",
  "enqueuedTime":"2021-01-29T16:45:39.143Z",
  "telemetry":{
    "temperature":8.341033560421833
  },
  "messageProperties":{
    "iothub-creation-time-utc":"2021-01-29T16:45:39.021Z"
  },
  "enrichments":{}
}
```

So how can we do this using this node?

**Comment by sandervandevelde** [comment]
Hello @hixfield,

check out this tutorial regarding sending a message: https://github.com/iotblackbelt/node-red-contrib-azure-iot-device/blob/master/USE.md#input-telemetry

From the top of my mind, this could look like this:

```
{
    'topic': 'telemetry',
    'payload': { 
        'temperature': 42
    },
    'properties': [                                           
       'iothub-creation-time-utc':'2021-01-29T16:45:39.021Z'
    ]
}
```

**Comment by hixfield** [comment]
@sandervandevelde thx for the feedback. I did notice the fact that I can send it like that. But will it then eventually be send to Azure IoT Hub via messageProperties?

**Comment by sandervandevelde** [comment]
Hello @hixfield,

yes, the mapping inside the node logic will turn this into a regular Azure IoT SDK message and send it to the IoT Hub. 

You can check this with the Azure IoT Explorer or via [code](https://sandervandevelde.wordpress.com/2018/02/13/take-back-control-over-iothub-messages-in-azure-functions/).

**Comment by iotblackbelt** [comment]
Based on information provided by @sandervandevelde I close this item.

**Comment by c-ortbauer** [comment]
Hello

Sry, for posting on a closed issue, but I cant get "iothub-creation-time-utc" to work.

When sending telemetry to Azure IoT-Central, I can't get a custom timestamp to work.
The messages show up in IoT-Central with automatically generated timestamps. 

Here is a example message:
```
{
    "payload": {
        "T": 24.490730144197755,
        "rH": 37.051956969558255
    },
    "topic": "telemetry",
    "_msgid": "75e50246d6969b53",
    "_event": "node:5ebfed4202d114de",
    "properties": [
        { "iothub-creation-time-utc": "2022-11-18T10:34:11.674Z" }
    ]
}
```

In Azure IoT-Central it shows up like this:
```
{
    "T": 24.490730144197755,
    "rH": 37.051956969558255,
    "_eventtype": "Telemetry",
    "_timestamp": "2022-11-18T10:38:09.369Z"
}
```

Is this not supported for IoT-Central, or am I doing something wrong.
Thanks in advance for any help!

**Comment by c-ortbauer** [comment]
My bad, I just found my mistake.

The instructions call for:
```
'properties': [                                           
       {'key':'<key>','value':<value>},
       ...
    ]
```
but i sent:
```
"properties": [
        { "iothub-creation-time-utc": "2022-11-18T10:34:11.674Z" }
    ]
```

It works perfectly when using it correctly:
```
msg.properties = [
    {'key':"iothub-creation-time-utc",'value':"2022-11-18T10:34:11.674Z"},
    ]
```
