### ISSUE TITLE
Sending telemetry with properties, wrong format?

### ISSUE THREAD

**Issue by hixfield** [iotblackbelt/node-red-contrib-azure-iot-device#29]
If I look at https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-messages-construct#application-properties-of-d2c-iot-hub-messages it indicates to send properties under a sub-object `messageProperties`

If I look at the manual here -> https://github.com/iotblackbelt/node-red-contrib-azure-iot-device/blob/master/USE.md#input-telemetry and also look in the node js code (as the code code still send them differently then the input message), I believe its sending them under "properties".

I think the module is wrongfully using "properties" and it should be `messageProperties`?

**Comment by sandervandevelde** [comment]
Hello @hixfield ,

the node is making use of the Node.JS SDK for Azure IoT. For an example on how a message is constructed, see this [example](https://github.com/Azure/azure-iot-sdk-node/blob/26695213809ff87e3e052c8f82de3be3a8afc066/device/samples/javascript/simple_sample_device.js#L61) (this example also sends a user properties name 'temperatureAlert'). 

The format you see [here](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-messages-construct#application-properties-of-d2c-iot-hub-messages) is a high-level description of the message as ingested in the IoT Hub. This is not the actual format sent by the device. The device typically only sends the 'telemetry' part. The rest is a construction showing iot hub data. 

The format used by the node has a specific structure so the internal node logic can make the right mapping. So 'properties' end up in 'messageProperties'.

I recommend playing around with this [MS Learn module](https://docs.microsoft.com/en-us/learn/paths/implement-iot-device-communication-by-using-azure-iot-sdks/) so you get a feeling about the Device-to-cloud communication.

**Comment by iotblackbelt** [comment]
Closed based on response given by @sandervandevelde.
