### ISSUE TITLE
[Feature] Additional Node Red node that connects to the Azure IoT Hub and can receive all messages sent to it

### ISSUE THREAD

**Issue by DavidDeeds** [iotblackbelt/node-red-contrib-azure-iot-device#31]
It's great that this project has modernised the use of Azure IoT _devices_ in NodeRed but it would be great if a new node was available that can receive all messages sent to the Azure IoT Hub. 

There is a similar capability here https://flows.nodered.org/node/node-red-contrib-azure-iot-hub (see the Azure IoT Hub Receiver node) but it's become quite outdated now.

Thanks!

**Comment by iotblackbelt** [comment]
> It's great that this project has modernised the use of Azure IoT _devices_ in NodeRed but it would be great if a new node was available that can receive all messages sent to the Azure IoT Hub.
> 
> There is a similar capability here https://flows.nodered.org/node/node-red-contrib-azure-iot-hub (see the Azure IoT Hub Receiver node) but it's become quite outdated now.
> 
> Thanks!

@DavidDeeds I have no intention to build that Node Red node. The approach your refer to is a server side node and requires server side authentication. This node is intended as a device node only. Don't want to mix up sever side and device side nodes into one. It would be reasonably simple to build a server side Node Red node using the Server side JS SDK.
