### ISSUE TITLE
Connection is not re-established when internet connection temporarily breaks for more than 5 minutes

### ISSUE THREAD

**Issue by dkby** [iotblackbelt/node-red-contrib-azure-iot-device#4]
Setting:
Using the node on Weidmueller u-controll web device (node red v1.1.2) . Provisioning with DPS (CA based x509).

Scenario for reproduction:
1. Node is online. Everything working as intended.
2. Internet connection breaks (pull ethernet connection). 
3. Try sending telemetry message.
4. Wait approx. 5 min.
5. Node goes to "error" state. Won't send or receive any more messages to and from iot hub even after the internet connection has been reestablished.

**Comment by iotblackbelt** [comment]
@dkby: problem resolved. Will be released with version 0.2.1.
