### ISSUE TITLE
Uncaught exception while stopping flows when offline

### ISSUE THREAD

**Issue by dkby** [iotblackbelt/node-red-contrib-azure-iot-device#7]
Setting:
Using the node on Weidmueller u-controll web device (node red v1.1.2) . Provisioning with DPS (CA based x509).

Scenario for reproduction:

1. Deploy application.
2. Wait until node is connected.
3. Break internet connection.
4. Redeploy or stop application

This leads to:
```
Dec 16 12:38:54 ucm node[5469]: 16 Dec 12:38:54 - [info] Stopping flows  
Dec 16 12:39:09 ucm node[5469]: 16 Dec 12:39:09 - [error] [azureiotdevice:d2662533.509318] Error stopping node: Close timed out  
Dec 16 12:39:09 ucm node[5469]: 16 Dec 12:39:09 - [info] Stopped flows 
```

**Comment by iotblackbelt** [comment]
@dkby: problem resolved. Will be released with version 0.2.1.
