### ISSUE TITLE
Device twin is not updated after reestablishing a temporally broken internet connection

### ISSUE THREAD

**Issue by dkby** [iotblackbelt/node-red-contrib-azure-iot-device#9]
Setting:
Using the node on Weidmueller u-controll web device (node red v1.1.2) . Provisioning with DPS (CA based x509).

Updates of the desired properties in the device twin are not received by the device when the updates occured while the device was temporarily offline.
A full device twin update is currently only requested by the node after deploying, but should be requested also when a broken connection is reestablished.

**Comment by iotblackbelt** [comment]
@dkby: problem resolved. Will be released with version 0.2.1.
